# Generated by Django 5.0.6 on 2024-06-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('firstName', models.CharField(blank=True, max_length=250)),
                ('lastName', models.CharField(blank=True, max_length=250)),
                ('phonenumber', models.IntegerField(blank=True)),
                ('authorization_code', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
    ]
