# Generated by Django 5.0.6 on 2024-06-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0002_customer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Customerr',
        ),
        migrations.AlterModelTable(
            name='customerr',
            table='Customerr',
        ),
    ]
