# Generated by Django 3.2.25 on 2026-01-22 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0003_rename_customer_customerr_alter_customerr_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_name', models.CharField(max_length=50)),
                ('color_code', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='product_variants')),
                ('stock', models.IntegerField(default=0)),
                ('is_default', models.BooleanField(default=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='lacesstore.product')),
            ],
            options={
                'unique_together': {('product', 'color_name')},
            },
        ),
    ]
