# Generated by Django 3.2.25 on 2026-01-22 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0005_cartitem_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='variant',
        ),
    ]
