# Generated by Django 3.2.25 on 2026-01-25 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0008_alter_cartitem_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='grand_total',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_cost',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
