# Generated by Django 3.2.25 on 2026-02-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0009_auto_20260125_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='currency',
            field=models.CharField(default='NGN', max_length=15),
        ),
    ]
