# Generated by Django 5.2.15 on 2026-06-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0010_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_image',
            field=models.ImageField(blank=True, null=True, upload_to='ordered_products/'),
        ),
    ]
