# Generated by Django 5.2.15 on 2026-06-17 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0011_orderitem_product_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customerr',
            new_name='Customer',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='lacesstore.customer'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
