# Generated by Django 4.2.16 on 2026-06-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0016_alter_order_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='youtube_video_id',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True, verbose_name='YouTube Video ID'),
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=XXXXXXXX)', max_length=500, null=True, verbose_name='YouTube Video URL'),
        ),
    ]
