# Generated by Django 4.2.16 on 2026-06-23 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0017_product_youtube_video_id_product_youtube_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=XXXXXXXXXXX or https://youtu.be/XXXXXXXXXXX)', max_length=500, null=True, verbose_name='YouTube Video URL'),
        ),
    ]
