# Generated by Django 4.2.16 on 2026-07-03 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lacesstore', '0018_alter_product_youtube_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='referer',
            field=models.URLField(blank=True, max_length=2000, null=True),
        ),
    ]
