# Generated by Django 3.2.25 on 2026-02-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('NGN', 'Naira'), ('USD', 'US Dollar'), ('GHS', 'Cedi'), ('XOF', 'CFA'), ('EUR', 'EURO')], default='NGN', max_length=3),
        ),
    ]
