# Generated by Django 3.2.25 on 2026-01-25 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping', '0002_cartshipping'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartShipping',
        ),
    ]
