# Generated by Django 4.2.16 on 2026-07-30 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor_products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'session_key')},
            },
        ),
        migrations.AddField(
            model_name='vendororder',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='vendororder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vendororder',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='additional_images',
            field=models.JSONField(blank=True, default=list, help_text='List of additional image URLs'),
        ),
        migrations.AlterField(
            model_name='vendorproduct',
            name='youtube_video_url',
            field=models.URLField(blank=True, help_text='Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=XXXXXXXXXXX)', max_length=500, null=True, verbose_name='YouTube Video URL'),
        ),
        migrations.CreateModel(
            name='VendorCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('shipping_address', models.TextField()),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='vendor_products.vendorcart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_products.vendorproduct')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendor_products.vendorproductvariant')),
            ],
        ),
    ]
